Implement Multiplatform support
saket/file-size pull request #10
Opened 2023-12-29 23:06 UTC by X1nto

# Additions
Supports the following platforms:
- JVM [x]
- iOS [x]
- macOS [x]
- JS [x]*
- Android []

*Tests are currently failing on JS and I have no idea why, will investigate. They're successful on macOS and JVM

# Changes
- Refactors the math functions to be platform-specific
- Migrates to kotlin.test for multiplatform tests
- Replaces the IllegalStateException with a custom FileSizePrecisionException (not really sure about the name, suggestions are more than welcome)
- Changes the names of the test functions, because Kotlin JS doesn't like spaces in names

# Caviats
Due to the fact that JS likes to be uniquely stupid, Kotlin doesn't support the `is` operators for any type of number except for Long, [since everything but Long is a JS Number ](https://kotlinlang.org/docs/js-to-kotlin-interop.html#kotlin-types-in-javascript). This results in the library relying on a `nonJs` source set, which separates JS decimal checking from normal Double checks.

2023-12-30 13:34 UTC, X1nto commented
I'm not sure that Linux and Windows support is possible without pulling in [TomMath](https://github.com/libtom/libtommath) or something like that, which I don't really know how to bind to Kotlin properly

2024-01-02 01:06 UTC, saket requested changes
thanks @X1nto!

2024-01-02 01:06 UTC, saket commented on build.gradle.kts
> +        languageVersion = JavaLanguageVersion.of(8)
Can you move this change to a separate PR? Including unrelated changes makes it difficult to review a PR.

2024-01-02 01:06 UTC, saket commented on gradle/libs.versions.toml
> +kotlin-test = { id = "org.jetbrains.kotlin" }
was this accidentally leftover?

2024-01-02 01:06 UTC, saket commented on library/src/commonTest/kotlin/me/saket/filesize/FileSizeTest.kt
> +  fun unitConversions() {
let's use underscores for making these test functions readable?

2024-01-02 01:06 UTC, saket commented on library/src/commonTest/kotlin/me/saket/filesize/FileSizeTest.kt
> +    assertEquals(expected = 2, actual = 2_000.bytes.inWholeKilobytes)
these assertion APIs from `kotlin.test` are terrible. what was the reason for moving away from assertk which is already multiplatform compatible?

2024-01-02 01:06 UTC, saket commented on library/src/commonMain/kotlin/me/saket/filesize/FileSize.kt
> +          throw FileSizePrecisionException()
Hmm I'm not convinced about the name either. Let's continue using `error()` for now?

2024-01-02 01:06 UTC, saket commented on library/src/jsMain/kotlin/me/saket/filesize/internals.js.kt
> +private external class BigDecimal(value: dynamic) {
Let's switch the storage of bytes from `Long` to `BigDecimal` in `FileSize`. I'm thinking that'll simplify a lot of code in this PR:

* Most of these `expect/actual` functions for math calculations will get moved to `commonMain`.
* This external class wouldn't need to exist
* We'd be able to add support for linux and windows.

https://github.com/ionspin/kotlin-multiplatform-bignum/

2024-01-02 22:06 UTC, X1nto commented on build.gradle.kts
> +        languageVersion = JavaLanguageVersion.of(8)
Sure, no problem

2024-01-02 22:08 UTC, X1nto commented on library/src/commonTest/kotlin/me/saket/filesize/FileSizeTest.kt
> +    assertEquals(expected = 2, actual = 2_000.bytes.inWholeKilobytes)
I converted them just to please some of the temporary source sets I made while migrating, I didn't think converting them back to assertk would be needed but sure, I can fix that

2024-01-02 22:14 UTC, X1nto commented on library/src/jsMain/kotlin/me/saket/filesize/internals.js.kt
> +private external class BigDecimal(value: dynamic) {
In this case, we can probably move all of the calculations to BigDecimal and most likely get rid of issues with Double/Float precision, should we explore that possibility?

2024-01-02 22:40 UTC, saket commented on library/src/jsMain/kotlin/me/saket/filesize/internals.js.kt
> +private external class BigDecimal(value: dynamic) {
yep yep yep!

2024-01-02 23:49 UTC, X1nto commented on library/src/commonMain/kotlin/me/saket/filesize/FileSize.kt
> +          throw FileSizePrecisionException()
No longer throwing anything, since the library can now handle doubles and floats

2024-01-02 23:50 UTC, X1nto commented
One thing concerning me now is the fact that the `throw_if_calculation_of_a_large_filesize_results_in_an_overflow` test is no longer necessary since the library now stores the bytes as BigDecimal, making it impossible to throw when FileSize with large numbers are constructed. Is this how we want to move forward? I'm looking forward to your input @saket since I'm not really sure if I'm doing that part correctly

2024-01-02 23:58 UTC, X1nto commented
Actually, the exception *will* be thrown as soon as the user calls any of the `FileSize#inWholeXxx` properties, as per `BigDecimal#longValue(exactValue = true)`, so there's that

2024-01-08 08:15 UTC, saket approved these changes
Kotlin is complaining about compilation errors, but I can fix them in a follow-up. Thanks a bunch @X1nto!

2024-01-08 08:16 UTC, merged

2024-01-08 08:20 UTC, X1nto commented
> Kotlin is complaining about compilation errors, but I can fix them in a follow-up. Thanks a bunch @X1nto!

Not gonna lie, haven't had any compilation errors but sometimes Intellij/gradle likes to skip over new errors if they appear deep in the development phase. You're welcome, love this project!

2024-01-08 08:26 UTC, saket commented
Were you able to resolve `@JvmName` and friends in your IDE despite the project being multiplatform?

2024-01-08 08:32 UTC, saket commented
This says I should be able to but I wonder what's missing: https://github.com/JetBrains/kotlin/blob/f45d92eebcfe3ac6c9b7f48c570f08eac9fce255/libraries/stdlib/common/src/kotlin/JvmAnnotationsH.kt#L43

2024-01-08 10:08 UTC, X1nto commented
> Were you able to resolve `@JvmName` and friends in your IDE despite the project being multiplatform?

Yes, those annotations are under the kotlin.jvm package and can be imported just like anything else. The only difference is that in a non-multiplatform environment, those annotations are imported implicitly.